<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:ns0="saibot.airport/services/utility/reference" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/top/CreateCountryDB" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction"
                xmlns:refData="saibot.airport/data/reference" xmlns:common="saibot.airport/data/common">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../Schemas/CountryService.xsd"/>
            <oracle-xsl-mapper:rootElement name="createCountryRequestMessage" namespace="saibot.airport/services/utility/reference"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../Resources/CreateCountryDB_table.xsd"/>
            <oracle-xsl-mapper:rootElement name="CmnCountriesCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/CreateCountryDB"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [TUE AUG 08 19:31:20 BRT 2017].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:CmnCountriesCollection>
         <xsl:for-each select="/ns0:createCountryRequestMessage/ns0:NewCountry">
            <tns:CmnCountries>
               <xsl:if test="refData:code">
                  <tns:code>
                     <xsl:value-of select="refData:code"/>
                  </tns:code>
               </xsl:if>
               <xsl:if test="refData:name">
                  <tns:name>
                     <xsl:value-of select="refData:name"/>
                  </tns:name>
               </xsl:if>
               <xsl:if test="refData:tailcode">
                  <tns:tailcode>
                     <xsl:value-of select="refData:tailcode"/>
                  </tns:tailcode>
               </xsl:if>
               <xsl:if test="refData:Flag">
                  <tns:flag>
                     <xsl:value-of select="refData:Flag"/>
                  </tns:flag>
               </xsl:if>
            </tns:CmnCountries>
         </xsl:for-each>
      </tns:CmnCountriesCollection>
   </xsl:template>
</xsl:stylesheet>
